spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CH04?serverTimezone=UTC
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create
