DROP DATABASE IF EXISTS CH02;
CREATE DATABASE CH02;

DROP DATABASE IF EXISTS CH04;
CREATE DATABASE CH04;

DROP DATABASE IF EXISTS CH05;
CREATE DATABASE CH05;

DROP DATABASE IF EXISTS CH06;
CREATE DATABASE CH06;

DROP DATABASE IF EXISTS CH07;
CREATE DATABASE CH07;

DROP DATABASE IF EXISTS CH08;
CREATE DATABASE CH08;